server :
  port : 8081

app :
  name: spring-config-project
  description: Microservice configuration

my:
  greeting: hello
  list:
    values: one,two,three

db:
  connection : test connection string here
  host : 129.0.0.1
  port : 2400

management:
  endpoints.web.exposure.include : "*"