server :
  port : 8081

app :
  name: spring-config-project
  description: Microservice configuration

management:
  endpoints.web.exposure.include : "*"


spring.cloud.config.uri: http://localhost:8888

spring:
  application:
    name: spring-boot-config
